services:
  redis:
    image: redis
    ports:
     - "56379:6379"
    networks:
      localnet:
        ipv4_address: 10.1.0.2

  ngx:
    image: fabiocicerchia/nginx-lua
    volumes:
     - ./lua_test.conf:/etc/nginx/conf.d/lua_test.conf:ro
     - ./firewall.lua:/etc/nginx/conf.d/firewall.lua:ro
     - ./api_add.lua:/etc/nginx/conf.d/api_add.lua:ro
    ports:
     - "8080:80"
    networks:
      localnet:
        ipv4_address: 10.1.0.3
    depends_on:
      - redis
    environment:
     - REDIS_HOST=10.1.0.2
     - REDIS_PORT=6379
     - NGINX_HOST=luatest.loc
     - NGINX_PORT=80

networks:
  localnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/16
          gateway: 10.1.0.1

