services:
  dtest:
    image: fabiocicerchia/nginx-lua
    volumes:
     - ./lua_test.conf:/etc/nginx/conf.d/lua_test.conf:ro
     - ./firewall.lua:/etc/nginx/conf.d/firewall.lua:ro
     - ./api_add.lua:/etc/nginx/conf.d/api_add.lua:ro
    ports:
     - "8080:80"
    networks:
     - devilbox
    environment:
     - NGINX_HOST=luatest.loc
     - NGINX_PORT=80

networks:
  devilbox:
    external:
      name: devilbox_app_net
